source 'http://rubygems.org'

# gem 'rspec'
gem 'rspec', github: 'rspec/rspec'
gem 'rspec-core', github: 'rspec/rspec-core'
gem 'rspec-mocks', github: 'rspec/rspec-mocks'
gem 'rspec-expectations', github: 'rspec/rspec-expectations'
gem 'rspec-support', github: 'rspec/rspec-support'
gem 'rspec-its'

gem 'bacon'

gem 'riot'

gem 'shoulda'

gem 'cucumber'

gem 'turnip'

gem 'spinach'

gem 'capybara'
gem 'selenium-webdriver'